// Autogenerated from Pigeon (v15.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class LaunchMessage {
  LaunchMessage({
    required this.url,
    required this.title,
    this.position = 0,
  });

  String url;

  String title;

  int position;

  Object encode() {
    return <Object?>[
      url,
      title,
      position,
    ];
  }

  static LaunchMessage decode(Object result) {
    result as List<Object?>;
    return LaunchMessage(
      url: result[0]! as String,
      title: result[1]! as String,
      position: result[2]! as int,
    );
  }
}

class VlcResultMessage {
  VlcResultMessage({
    required this.position,
    required this.duration,
  });

  int position;

  int duration;

  Object encode() {
    return <Object?>[
      position,
      duration,
    ];
  }

  static VlcResultMessage decode(Object result) {
    result as List<Object?>;
    return VlcResultMessage(
      position: result[0]! as int,
      duration: result[1]! as int,
    );
  }
}

class _VlcLauncherHostApiCodec extends StandardMessageCodec {
  const _VlcLauncherHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LaunchMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return LaunchMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class VlcLauncherHostApi {
  /// Constructor for [VlcLauncherHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VlcLauncherHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _VlcLauncherHostApiCodec();

  Future<bool> isVlcInstalled() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.zen_player.VlcLauncherHostApi.isVlcInstalled';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  Future<bool> launchVideo(LaunchMessage message) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.zen_player.VlcLauncherHostApi.launchVideo';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[message]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }
}

class _VlcLauncherFlutterApiCodec extends StandardMessageCodec {
  const _VlcLauncherFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is VlcResultMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return VlcResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class VlcLauncherFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _VlcLauncherFlutterApiCodec();

  void onVlcResult(VlcResultMessage message);

  static void setup(VlcLauncherFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.zen_player.VlcLauncherFlutterApi.onVlcResult', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.zen_player.VlcLauncherFlutterApi.onVlcResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VlcResultMessage? arg_message = (args[0] as VlcResultMessage?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.zen_player.VlcLauncherFlutterApi.onVlcResult was null, expected non-null VlcResultMessage.');
          try {
            api.onVlcResult(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
